spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksy_mate_db
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: rentacartobeto@gmail.com
    password: "tupu oavl qdgi mpbf"
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          write-timeout: 10000
          connection-timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            port: 587
    verify:
      host: http://localhost:8088
#  mail:
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#          starttls:
#            enable: true
#            required: true
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    host: localhost
#    port: 1025


application:
  security:
    jwt:
      secret-key: 85dbe15d75ef9308c7ae0f33c7a324cc6f4bf519a2ed2f3027bd33c140a4f9aa
      expiration: 86400000
      refresh-token:
        expiration: 604800000 # 7 days

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088


