services:
  postgres:
    container_name: postgres-sql-booksy-mate
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: booksy_mate_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-booksy-mate
    image: maildev/maildev
    ports:
      - 1080:80
      - 1025:25
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local